### ISSUE TITLE
Need a quick fix for this

### ISSUE THREAD

**Issue by sakshyamdahal** [eddiem3/live-chair#18]
with this api call https://fathomless-temple-1065.herokuapp.com/api/v1/users/barbers

you get a json response that looks like:

[
{
user: {
id: 1,
fname: "Sam",
lname: "Wan"
}
},
{
user: {
id: 2,
fname: "Ik",
lname: "Tu"
}
},
{
user: {
id: 3,
fname: "Md",
lname: "Trih"
}
},
{
user: {
id: 5,
fname: "Ed",
lname: "Fur"
}
}
]

all i want is instead of user 'id' return the profile 'id' without changing anything for the same api call.

**Comment by sakshyamdahal** [comment]
The reason this is important is that when displaying the barbers i only have this 'id' to identify who a user clicked on. But to display the profile of the barber i would need his profile id instead of user id.. and since profile id and user id for barbers maybe different this fix is necessary.

**Comment by eddiem3** [comment]
Working on it now. Give me a sec. My webrick server isn't working smh

**Comment by eddiem3** [comment]
Check my pull request and I'll merge

**Comment by sakshyamdahal** [comment]
awesome
